### ISSUE TITLE
Card.isValid() does not check valid quantity of special energy, or specific restrictions like ◊ or Ace Spec. cards

### ISSUE THREAD

**Issue by mcwilbur** [delfoxav/PTCGODeckListExporter#1]
In the Card.types list there is no differentiation between basic and special energy. There is also no verification for specific restrictions like ◊ (Prism) or Ace Spec. cards which limit quantities to respectively 1 per name and 1 per deck.

**Comment by delfoxav** [comment]
Thanks for pointing out these issues. I added multiples attributes to the Card type (isBasicNrj, isPrism and isAcespec) to handle them. I also created some __add__ and __iadd__ method for the Card type. And now there is a control when adding a card to deck to check if there is more than 4 cards with the same name, more than 1 acespec or more than 2 prism with the same name.
